### ISSUE TITLE
Spacemacs Rocks 第二季: Day 14 - Day 21 Roadmap

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/Spacemacs-rocks#93]
- [x] 常用 Spacemacs 操作（1）：file 和 buffer 操作
- [x] 常用 Spacemacs 操作 （2）：window，project和 layout 操作
- [x] Ctags 和 company mode 配置自动补全
- [x] Lispy 的使用
- [x] Emacs 新手如何存活
- [x] 调试 elisp和扩展 emacs,编写自己的 minor-mode
- [x] Revisit my Spacemacs configure: introduce more tips and inspire people who also using Spacemacs
- [x] 后续如何学习，如何一年成为 Emacs 高手

**Comment by zilongshanren** [comment]
第二季视频已经全部录制完成，这两天会全部上传，大家再也不要追剧了，我也再也不要被人追着更新啦
